name: Release GitHub Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Release GitHub Page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Deploy to github page
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
